name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧰 Maintenance'
    label: 'chore'

autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/' # branches starting with "chore/"
  - label: 'bug'
    branch:
      - '/bugfix\/.+/' # branches starting with "bugfix/"
  - label: 'enhancement'
    branch:
      - '/feature\/.+/' # branches starting with "feature/"

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes

  $CHANGES