version: "3.9"
services:
  db:
    environment:
      POSTGRES_DB: mealfriend_development
      POSTGRES_USER: local-dev
      POSTGRES_PASSWORD: password
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    depends_on:
      - db
    environment:
      # Extracted from: postgres://local-dev:password@db/mealfriend_development
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: mealfriend_development
      PGUSER: local-dev
      PGPASSWORD: password
      # Configure DB migration helpers:
      # - https://github.com/pressly/goose
      # - https://www.postgresql.org/docs/13/app-pgdump.html
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://local-dev:password@db/mealfriend_development?sslmode=disable

    volumes:
      - .:/app
      - godeps:/go/pkg/mod/cache

volumes:
  pgdata:
  godeps:
