version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: your_password
    ports:
      - "50051:50051"
    volumes:
      - .:/app
      - godeps:/go/pkg/mod/cache

  neo4j:
    environment:
      NEO4J_AUTH: neo4j/your_password
    image: neo4j:5.10
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
    healthcheck:
        test: wget http://localhost:7474 || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 3s

volumes:
  godeps:
  neo4jdata:
