// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0
// source: protos/mealfriend.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag int32

const (
	Tag_TAG_UNSPECIFIED Tag = 0
	Tag_TAG_BEEF        Tag = 1
	Tag_TAG_DAIRY       Tag = 2
	Tag_TAG_EGG         Tag = 3
	Tag_TAG_FISH        Tag = 4
	Tag_TAG_FRUIT       Tag = 5
	Tag_TAG_GRAIN       Tag = 6
	Tag_TAG_LEGUMES     Tag = 7
	Tag_TAG_PASTA       Tag = 8
	Tag_TAG_PORK        Tag = 9
	Tag_TAG_POULTRY     Tag = 10
	Tag_TAG_SHELLFISH   Tag = 11
	Tag_TAG_VEGETABLE   Tag = 12
)

// Enum value maps for Tag.
var (
	Tag_name = map[int32]string{
		0:  "TAG_UNSPECIFIED",
		1:  "TAG_BEEF",
		2:  "TAG_DAIRY",
		3:  "TAG_EGG",
		4:  "TAG_FISH",
		5:  "TAG_FRUIT",
		6:  "TAG_GRAIN",
		7:  "TAG_LEGUMES",
		8:  "TAG_PASTA",
		9:  "TAG_PORK",
		10: "TAG_POULTRY",
		11: "TAG_SHELLFISH",
		12: "TAG_VEGETABLE",
	}
	Tag_value = map[string]int32{
		"TAG_UNSPECIFIED": 0,
		"TAG_BEEF":        1,
		"TAG_DAIRY":       2,
		"TAG_EGG":         3,
		"TAG_FISH":        4,
		"TAG_FRUIT":       5,
		"TAG_GRAIN":       6,
		"TAG_LEGUMES":     7,
		"TAG_PASTA":       8,
		"TAG_PORK":        9,
		"TAG_POULTRY":     10,
		"TAG_SHELLFISH":   11,
		"TAG_VEGETABLE":   12,
	}
)

func (x Tag) Enum() *Tag {
	p := new(Tag)
	*p = x
	return p
}

func (x Tag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tag) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_mealfriend_proto_enumTypes[0].Descriptor()
}

func (Tag) Type() protoreflect.EnumType {
	return &file_protos_mealfriend_proto_enumTypes[0]
}

func (x Tag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tag.Descriptor instead.
func (Tag) EnumDescriptor() ([]byte, []int) {
	return file_protos_mealfriend_proto_rawDescGZIP(), []int{0}
}

type GetMealPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requirements map[string]int32 `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetMealPlanRequest) Reset() {
	*x = GetMealPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mealfriend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMealPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealPlanRequest) ProtoMessage() {}

func (x *GetMealPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mealfriend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealPlanRequest.ProtoReflect.Descriptor instead.
func (*GetMealPlanRequest) Descriptor() ([]byte, []int) {
	return file_protos_mealfriend_proto_rawDescGZIP(), []int{0}
}

func (x *GetMealPlanRequest) GetRequirements() map[string]int32 {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type GetMealPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipes []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
}

func (x *GetMealPlanResponse) Reset() {
	*x = GetMealPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mealfriend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMealPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealPlanResponse) ProtoMessage() {}

func (x *GetMealPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mealfriend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealPlanResponse.ProtoReflect.Descriptor instead.
func (*GetMealPlanResponse) Descriptor() ([]byte, []int) {
	return file_protos_mealfriend_proto_rawDescGZIP(), []int{1}
}

func (x *GetMealPlanResponse) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type ScrapeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ScrapeRequest) Reset() {
	*x = ScrapeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mealfriend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeRequest) ProtoMessage() {}

func (x *ScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mealfriend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeRequest.ProtoReflect.Descriptor instead.
func (*ScrapeRequest) Descriptor() ([]byte, []int) {
	return file_protos_mealfriend_proto_rawDescGZIP(), []int{2}
}

func (x *ScrapeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ScrapeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipe *Recipe `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mealfriend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mealfriend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_protos_mealfriend_proto_rawDescGZIP(), []int{3}
}

func (x *ScrapeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type Recipe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Source      string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Ingredients []string `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Tags        []Tag    `protobuf:"varint,5,rep,packed,name=tags,proto3,enum=mealfriend.Tag" json:"tags,omitempty"`
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mealfriend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mealfriend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_protos_mealfriend_proto_rawDescGZIP(), []int{4}
}

func (x *Recipe) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Recipe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipe) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Recipe) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *Recipe) GetTags() []Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_protos_mealfriend_proto protoreflect.FileDescriptor

var file_protos_mealfriend_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x61, 0x6c, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x65, 0x61, 0x6c, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x22, 0xab, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61,
	0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x0c,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x1a, 0x3f, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x43, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x50, 0x6c,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65,
	0x61, 0x6c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52,
	0x07, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x53, 0x63, 0x72, 0x61,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x3c, 0x0a, 0x0e, 0x53,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6d, 0x65, 0x61, 0x6c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x06, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x67, 0x72, 0x65,
	0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x2a, 0xd5, 0x01, 0x0a, 0x03,
	0x54, 0x61, 0x67, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x41, 0x47, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x41, 0x47, 0x5f,
	0x42, 0x45, 0x45, 0x46, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x41, 0x47, 0x5f, 0x44, 0x41,
	0x49, 0x52, 0x59, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x41, 0x47, 0x5f, 0x45, 0x47, 0x47,
	0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x41, 0x47, 0x5f, 0x46, 0x49, 0x53, 0x48, 0x10, 0x04,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x41, 0x47, 0x5f, 0x46, 0x52, 0x55, 0x49, 0x54, 0x10, 0x05, 0x12,
	0x0d, 0x0a, 0x09, 0x54, 0x41, 0x47, 0x5f, 0x47, 0x52, 0x41, 0x49, 0x4e, 0x10, 0x06, 0x12, 0x0f,
	0x0a, 0x0b, 0x54, 0x41, 0x47, 0x5f, 0x4c, 0x45, 0x47, 0x55, 0x4d, 0x45, 0x53, 0x10, 0x07, 0x12,
	0x0d, 0x0a, 0x09, 0x54, 0x41, 0x47, 0x5f, 0x50, 0x41, 0x53, 0x54, 0x41, 0x10, 0x08, 0x12, 0x0c,
	0x0a, 0x08, 0x54, 0x41, 0x47, 0x5f, 0x50, 0x4f, 0x52, 0x4b, 0x10, 0x09, 0x12, 0x0f, 0x0a, 0x0b,
	0x54, 0x41, 0x47, 0x5f, 0x50, 0x4f, 0x55, 0x4c, 0x54, 0x52, 0x59, 0x10, 0x0a, 0x12, 0x11, 0x0a,
	0x0d, 0x54, 0x41, 0x47, 0x5f, 0x53, 0x48, 0x45, 0x4c, 0x4c, 0x46, 0x49, 0x53, 0x48, 0x10, 0x0b,
	0x12, 0x11, 0x0a, 0x0d, 0x54, 0x41, 0x47, 0x5f, 0x56, 0x45, 0x47, 0x45, 0x54, 0x41, 0x42, 0x4c,
	0x45, 0x10, 0x0c, 0x32, 0xa1, 0x01, 0x0a, 0x0a, 0x4d, 0x65, 0x61, 0x6c, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x12, 0x50, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x50, 0x6c, 0x61,
	0x6e, 0x12, 0x1e, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x12, 0x19,
	0x2e, 0x6d, 0x65, 0x61, 0x6c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x53, 0x63, 0x72, 0x61,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x65, 0x61, 0x6c,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x2d, 0x68, 0x6f, 0x68,
	0x6e, 0x2f, 0x6d, 0x65, 0x61, 0x6c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_mealfriend_proto_rawDescOnce sync.Once
	file_protos_mealfriend_proto_rawDescData = file_protos_mealfriend_proto_rawDesc
)

func file_protos_mealfriend_proto_rawDescGZIP() []byte {
	file_protos_mealfriend_proto_rawDescOnce.Do(func() {
		file_protos_mealfriend_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_mealfriend_proto_rawDescData)
	})
	return file_protos_mealfriend_proto_rawDescData
}

var file_protos_mealfriend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_mealfriend_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_mealfriend_proto_goTypes = []interface{}{
	(Tag)(0),                    // 0: mealfriend.Tag
	(*GetMealPlanRequest)(nil),  // 1: mealfriend.GetMealPlanRequest
	(*GetMealPlanResponse)(nil), // 2: mealfriend.GetMealPlanResponse
	(*ScrapeRequest)(nil),       // 3: mealfriend.ScrapeRequest
	(*ScrapeResponse)(nil),      // 4: mealfriend.ScrapeResponse
	(*Recipe)(nil),              // 5: mealfriend.Recipe
	nil,                         // 6: mealfriend.GetMealPlanRequest.RequirementsEntry
}
var file_protos_mealfriend_proto_depIdxs = []int32{
	6, // 0: mealfriend.GetMealPlanRequest.requirements:type_name -> mealfriend.GetMealPlanRequest.RequirementsEntry
	5, // 1: mealfriend.GetMealPlanResponse.recipes:type_name -> mealfriend.Recipe
	5, // 2: mealfriend.ScrapeResponse.recipe:type_name -> mealfriend.Recipe
	0, // 3: mealfriend.Recipe.tags:type_name -> mealfriend.Tag
	1, // 4: mealfriend.Mealfriend.GetMealPlan:input_type -> mealfriend.GetMealPlanRequest
	3, // 5: mealfriend.Mealfriend.Scrape:input_type -> mealfriend.ScrapeRequest
	2, // 6: mealfriend.Mealfriend.GetMealPlan:output_type -> mealfriend.GetMealPlanResponse
	4, // 7: mealfriend.Mealfriend.Scrape:output_type -> mealfriend.ScrapeResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_mealfriend_proto_init() }
func file_protos_mealfriend_proto_init() {
	if File_protos_mealfriend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_mealfriend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMealPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mealfriend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMealPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mealfriend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrapeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mealfriend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrapeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mealfriend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recipe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_mealfriend_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_mealfriend_proto_goTypes,
		DependencyIndexes: file_protos_mealfriend_proto_depIdxs,
		EnumInfos:         file_protos_mealfriend_proto_enumTypes,
		MessageInfos:      file_protos_mealfriend_proto_msgTypes,
	}.Build()
	File_protos_mealfriend_proto = out.File
	file_protos_mealfriend_proto_rawDesc = nil
	file_protos_mealfriend_proto_goTypes = nil
	file_protos_mealfriend_proto_depIdxs = nil
}
