# refs:
# - https://github.com/actions/starter-workflows/blob/main/ci/go.yml
# - https://github.com/golangci/golangci-lint-action

name: PR Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: Test
        run: go test -v ./...